credentials:

  usernames:

    jsmith:

      email: jsmith@gmail.com

      name: John Smith

      password: 'contrase√±a_hasheada' # No usar texto plano

    camilacordoba:

      email: camicordoba5@gmail.com

      name: Camila Cordoba

      password: 'Mosaico98.'

cookie:

  expiry_days: 30

  key: some_signature_key

  name: some_cookie_name
